metadata.config_version_wildcard = "*"

[game_setup]
roblox_version = '2018'

enable_saveplace = false

[game_setup.persistence]
sqlite_path = '_.sqlite'
clear_on_start = false

[server_core.place_file]
rbxl_uri = './Crossroads.rbxl'

[server_core.metadata]
title = 'Crossroads'
description = 'The classic Rōblox map.'
creator_name = 'David Baszucki, Erik Cassel'
icon_uri = 'https://ia600506.us.archive.org/34/items/soundcloud-1509042007/1509042007.jpg'


[server_core]
startup_script = 'game.workspace.FilteringEnabled = true'

retrieve_default_user_code = '''
function(tick) -- float -> str
    return string.format('Player%d', tick)
end
'''

check_user_allowed = '''
function(user_iden, user_code) -- string -> bool
    return true
end
'''

retrieve_avatar_type = '''
function(user_iden, user_code) -- str -> str
    return 'R15'
end
'''

retrieve_avatar_items = '''
function(user_iden, user_code) -- str -> [str]
    return {}
end
'''

#Please refer to this page for avatar colors. https://create.roblox.com/docs/reference/engine/datatypes/BrickColor

retrieve_avatar_colors = '''
function(user_iden, user_code) -- str -> {[str]: number}
    return {
        head = BrickColor.Random().Number,
        left_arm = BrickColor.Random().Number,
        left_leg = BrickColor.Random().Number,
        right_arm = BrickColor.Random().Number,
        right_leg = BrickColor.Random().Number,
        torso = BrickColor.Random().Number,
    }
end
'''

retrieve_avatar_scales = '''
def f(*a):
    return {
        "height": 1,
        "width": 1,
        "head": 1,
        "depth": 1,
        "proportion": 0,
        "body_type": 0,
    }
'''

retrieve_username = '''
def f(user_id_num, user_code):
    return user_code
'''

filter_text = '''
def f(text, user_id_num, user_code):
    return (
        text
        .replace('oo','òó')
        .replace('OO','ÒÓ')
        .replace('ee','èé')
        .replace('EE','ÈÉ')
        .replace('Roblox','Rōblox')
        .replace('ROBLOX','RŌBLOX')
    )
'''

retrieve_groups = '''
function(user_iden, user_code) -- str -> str
    return {
        ['1200769'] = 255;
        ['2868472'] = 255;
        ['4199740'] = 255;
        ['4265462'] = 255;
        ['4265456'] = 255;
        ['4265443'] = 255;
        ['4265449'] = 255;
    }
end
'''

retrieve_default_funds = '''
def f(*a):
    return 6969
'''

chat_style = 'ClassicAndBubble'
