metadata.config_version_wildcard = "*"

[game_setup]
roblox_version = '2018'

enable_saveplace = false

[game_setup.persistence]
sqlite_path = '_.sqlite'
clear_on_start = false

[server_core.place_file]
rbxl_uri = './Crossroads.rbxl'

[server_core.metadata]
title = 'Crossroads'
description = 'The classic Rōblox map.'
creator_name = 'David Baszucki, Erik Cassel'
icon_uri = 'https://ia600506.us.archive.org/34/items/soundcloud-1509042007/1509042007.jpg'


[server_core]
startup_script = 'game.workspace.FilteringEnabled = true'

retrieve_default_user_code = '''
def f(user_iden, user_code) -> bool:
    return True
'''

check_user_allowed = '''
def f(user_iden, user_code) -> bool:
    return True
'''

retrieve_avatar_type = '''
def f(user_iden, user_code) -> str:
    return 'R15'
'''

retrieve_avatar_items = '''
function(user_iden, user_code)
    if user_code == 'VisualPlugin' then
        return {
            10726856854,
            9482991343,
            9481782649,
            9120251003,
            4381817635,
            6969309778,
            5731052645,
            2846257298,
            121390054,
            261826995,
            154386348,
            201733574,
            48474294,
            6340101,
            192483960,
            190245296,
            183808364,
            34247191,
        }
    elseif user_code == 'Twig' then
        return {
            73157519528855,
            5247028511,
            5247028779,
            4954433794,
            4954439703,
        }
    end
    return {}
end
'''

# Please refer to this page for avatar colors. https://create.roblox.com/docs/reference/engine/datatypes/BrickColor
# We're using a Lua function here for direct access to `BrickColor.Random().Number`.

retrieve_avatar_colors = '''
function(user_iden, user_code) -- str -> {[str]: number}
    return {
        head = BrickColor.Random().Number,
        left_arm = BrickColor.Random().Number,
        left_leg = BrickColor.Random().Number,
        right_arm = BrickColor.Random().Number,
        right_leg = BrickColor.Random().Number,
        torso = BrickColor.Random().Number,
    }
end
'''

retrieve_avatar_scales = '''
def f(user_id_num, user_code):
    return {
        "height": 1,
        "width": 1,
        "head": 1,
        "depth": 1,
        "proportion": 0,
        "body_type": 0,
    }
'''

retrieve_username = '''
def f(user_id_num, user_code):
    return user_code
'''

filter_text = '''
def f(text, user_id_num, user_code):
    return (
        text
        .replace('oo','òó')
        .replace('OO','ÒÓ')
        .replace('ee','èé')
        .replace('EE','ÈÉ')
        .replace('Roblox','Rōblox')
        .replace('ROBLOX','RŌBLOX')
    )
'''

retrieve_groups = '''
def f(user_iden, user_code):
    return {
        '1200769': 255,
        '2868472': 255,
        '4199740': 255,
        '4265462': 255,
        '4265456': 255,
        '4265443': 255,
        '4265449': 255,
    }
'''

retrieve_default_funds = '''
def f(*a):
    return 6969
'''

chat_style = 'ClassicAndBubble'
