[game_setup]
roblox_version = '2021'

[server_core.place_file]
rbxl_uri = '_.rbxl'
track_file_changes = true

[game_setup.database]
path = '_.sqlite'
clear_on_start = false

[server_core.metadata]
title = 'A Long Q Shall Emerge!'
description = ''
creator.name = 'ÒÓ'
icon_uri = 'https://ussopload.wikimedia.org/wikipedia/commons/0/0b/Write_machine.jpg'

[server_core]
retrieve_default_user_code = '''
function(tick) -- float -> str
    return 'VisualPlugin'
end
'''

check_user_allowed = '''
def f(user_iden, user_code) -> bool:
    return True
'''

retrieve_avatar_type = '''
def f(user_iden, user_code) -> str:
    return 'R15'
'''

retrieve_avatar_items = '''
function(user_iden, user_code)
    return {
        10726856854,
        9482991343,
        9481782649,
        9120251003,
        4381817635,
        6969309778,
        5731052645,
        2846257298,
        121390054,
        261826995,
        154386348,
        201733574,
        48474294,
        6340101,
        192483960,
        190245296,
        183808364,
        34247191,
    }
end
'''

retrieve_avatar_colors = '''
def f(user_iden, user_code):
    return {
        "head": 315,
        "left_arm": 315,
        "left_leg": 315,
        "right_arm": 315,
        "right_leg": 315,
        "torso": 315,
    }
'''

retrieve_avatar_scales = '''
def f(user_iden, user_code):
    return {
        "height": 1,
        "width": 1,
        "head": 1,
        "depth": 1,
        "proportion": 0,
        "body_type": 0,
    }
'''

retrieve_username = '''
def f(user_id_num, user_code):
    return user_code
'''

retrieve_user_id = '''
import random
def f(user_code) -> int:
    return random.randint(1, 16777216)
'''

retrieve_account_age = '''
def f(*a):
    return 6969
'''

filter_text = '''
def f(text, user_id_num, user_code):
    return (
        text
        .replace('oo','òó')
        .replace('OO','ÒÓ')
        .replace('ee','èé')
        .replace('EE','ÈÉ')
        .replace('Roblox','Rōblox')
        .replace('ROBLOX','RŌBLOX')
    )
'''

chat_style = 'ClassicAndBubble'
